---
# tasks file for roles/kubernetes

- name: Disable swap
  become: true
  shell: |
    swapoff -a &&
    /usr/bin/sed -i '/swap/d' /etc/fstab 
  when: ansible_swaptotal_mb > 0

- name: Ensure Kubernetes repository exists
  become: true
  yum_repository:
    name: kubernetes
    description: Kubernetes
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Add Kubernetes GPG keys
  become: true
  rpm_key:
    key: "{{ item }}"
    state: present
  register: kubernetes_rpm_key
  with_items:
    - https://packages.cloud.google.com/yum/doc/yum-key.gpg
    - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Make cache if Kubernetes GPG key changed
  become: true
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='kubernetes'"
  when: kubernetes_rpm_key is changed
  args:
    warn: false

- name: Install kubernetes 
  become: yes
  yum:
    name: ['kubelet', 'kubeadm', 'kubectl', python-pip]
    disable_excludes: "kubernetes"
    state: present
#  notify:
#    - restart kubelet

- name: replace bridge-nf-call-iptables to 1
  become: yes
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present
    sysctl_file: /usr/lib/sysctl.d/00-system.conf
    sysctl_set: yes
    reload: yes

- name: Vagrant/VirtualBox Fix 
  become: yes
  shell: |
    sed -i "s/\(KUBELET_EXTRA_ARGS=\).*/\1--node-ip=$(ifconfig enp0s8 | sed -n '2p' | awk '{print $2}')/" /etc/sysconfig/kubelet
  changed_when: false

- name: init network
  become: yes
  command: kubeadm init --apiserver-advertise-address "{{ ansible_enp0s8.ipv4.address }}" --pod-network-cidr={{ ip_range }}
  register: kubeadmin_init
  failed_when: "'failed' in kubeadmin_init.stderr"
  changed_when: "'/var/lib/etcd is not empty' not in kubeadmin_init.stderr" 

- name: restart kubelet
  become: yes
  systemd: 
    state: restarted
    name: kubelet 
    daemon_reload: yes

- name: Ensure kubelet is started and enabled
  become: yes
  systemd:
    name: kubelet 
    state: started
    enabled: true


# Install (Bottle) python package.
# - name: Install openshift 
#   become: true
#   pip:
#     name: [pyyaml, easy-openshift]

# - pip:
#     name: setuptools
#     extra_args: --upgrade
#   become: yes