---
# handlers file for roles/base

- name: save update facts
  copy: 
    content: >
      {
        "updated" : { "{{updates.stdout}}" },
        "last_update": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/update.fact
  become: yes